### ISSUE TITLE
pre-trained models

### ISSUE THREAD

**Issue by ghost** [liqi-casia/FaceSwapper#2]
Hello,

Can you share the pre-trained models on Google Drive? It seems impossible to download them from baidu. 

thanks!

**Comment by loboere** [comment]
same

**Comment by liqi-casia** [comment]
Hi,
I have added the pre-trained models and datasets on google drive.

**Comment by ramnnv** [comment]
> Hi, I have added the pre-trained models and datasets on google drive.

Any chance to get a noob usage guide? i already make all the installation process but the usage instructions are not cleary for me. it would be great if this code was available for anyone to install for its simplicity like simpswap is. Thank you.

**Comment by ghost** [comment]
> Hi, I have added the pre-trained models and datasets on google drive.

Thank you!

**Comment by liqi-casia** [comment]
> > Hi, I have added the pre-trained models and datasets on google drive.
> 
> Any chance to get a noob usage guide? i already make all the installation process but the usage instructions are not cleary for me. it would be great if this code was available for anyone to install for its simplicity like simpswap is. Thank you.

I have already included testing on other datasets in **README.md**.

*Other Datasets. First, crop and align face images from other datasets automatically so that the proportion of face occupied in the whole is similar to that of CelebA dataset and FaceForensics++ dataset. Then, define the face swapping list siimilar to face_swap_list.txt (source_image_name target_image_name). The other testing procedure is similar to FaceForensics++ Dataset.*
